name: HeroKu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: juttamejias/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          stack: "container"
          usedocker: true
          docker_build_args: |
            SQL_DSN
            TZ
        env:
          SQL_DSN: ${{secrets.NEW_API_DATABASE}}
          TZ: Asia/Shanghai
